### ISSUE TITLE
closed captions

### ISSUE THREAD

**Issue by sleek-gramps** [aussieaddons/plugin.video.abc_iview#3074]
saw #1909 but closed captions not working at the moment.  Using Kodi 17.3 and ABC Iview 1.8  Important as I am hearing impaired.  thanks.

**Comment by glennguy** [comment]
Hey @sleek-gramps 

I can see the issue - ABC seem to have discontinued using their custom subtitles format in favour of a more widely used format. I'll get onto it ASAP, should have a fix ready to go for you tomorrow.

**Comment by glennguy** [comment]
@sleek-gramps Closed captions are working again, a new version is available in the main repo
