### ISSUE TITLE
Subtitles on by default

### ISSUE THREAD

**Issue by mpember** [aussieaddons/plugin.video.abc_iview#3078]
Why was the setting to control the default settings for the display of subtitles removed?

Is there a different setting that I should be looking for?

Thanks

**Comment by glennguy** [comment]
The setting that used to be there enabled/disabled subtitles for iView - it
had nothing to do with setting a default. If you want to change the default
for subtitles, the next time you watch a video bring up the OSD
(OK/touch/enter) and go to the audio and subtitle settings. From there
enable or disable subtitles and select 'set as default for all media'. That
should do the trick!

**Comment by mpember** [comment]
Since the only time I need (or even see) subtitles is when I download a subtitle file for a video file, I have never bothered to change from whatever the default setting has been.  As I had only started seeing them in iView, I figured it was a result of a change in the plugin.  I have changed the setting for 'all media' and the subtitles have gone.

Thanks.
