### ISSUE TITLE
Kodi Install Fail "Common Plugin Cache Failed To Install"

### ISSUE THREAD

**Issue by Stombell** [aussieaddons/plugin.video.abc_iview#3079]
Having problems with both ABCiView and SBSOnDemand addon installations.  Getting "Failed To Install Dependency" error.  Noting "Common Plugin Cache Failed To Install" during installation process.
Perhaps related to these stations now requiring sign-in?

Plus7, TenPlay and 9Now all installed OK.
Toshiba laptop, WIndows 10, Kodi Build 17.6

**Comment by andybotting** [comment]
Nah, nothing to do with those services requiring login. It will have
something to do with that common cache plugin, which is not one of ours.

It would be quite helpful if you could send us an error report about it,
after attempting the install again. You can do it though the settings of
any of our other add-ons that you have installed.

Then just send us though the URL it gives you.

Thanks!

**Comment by Stombell** [comment]
I tried to turn on Settings>Debugging and then viewing the error log once I got another fail.  Gave me the same errors without any detail.  Is there some other logging mechanism you're referring to?  How do I turn on the logging you're after? Paul BellMobile +61 401 698 173

**Comment by Stombell** [comment]
Hi Andy, there were some common files I had the option to reinstall, so I did.  Now I have iView and SBS On Demand.  I wish I could remember the exact name of those common files for you.
But thanks for all your efforts in this area (not just today's efforts, but all the effort you guys have put into these add ons).
Cheers, Paul BellMobile +61 401 698 173

**Comment by andybotting** [comment]
cheers Paul.

Everything working for you now?

**Comment by Stombell** [comment]
Working great!!! Thanks again. Paul BellMobile +61 401 698 173

**Comment by anthony9999** [comment]
Hi

I have same issue with SBS and Iview. How did you get to reinstall those common files?

Thank

**Comment by Stombell** [comment]
I'm a little embarrassed I can't say exactly, but I do know I was in an area listing Addon Dependencies (I was also bouncing back and forth between Estuary skin and Aeon skin, I don't know which skin I found this area).  The listing had an option to reinstall the dependency, so I reinstalled everything that had "common" in its name. And it worked. 

Cheers,

Paul Bell
Mobile# +61 401 698 173

**Comment by Stombell** [comment]
Figured it out.  Just got a Raspberry Pi with Kodi last night and had the same issue (Common Addon Methods failed to update).  Here's what I did:
1)  In Settings>System>Addons>Manage Dependencies.2) Open "Common Addon Methods". 3) Open Update4) Select Version 2.0.0 from Local Package Cache.  Package will update to that version.  SBS Ondemand and ABC iView should now work.5) Repeat steps 1,2 & 3 but this time pick the package that has the newest version (in my case it was 2.0.1 from Ares Project) and update to that version. SBS Ondemand and ABC iView should still wor.
Apparently there is something in that Local Cache Version that is not in any other version.  It also appears whatever that Local Cache Version does "sticks" because updating the dependency to another non-Local Cache version doesn't override what the Local Cache version did.
Cheers,
Paul BellMobile +61 401 698 173

**Comment by anthony9999** [comment]
Thanks!

**Comment by anthony9999** [comment]
After trying all that dependency stuff still same problem... some_logging below_
•
1:56:51.129 7:18446744071922112816 ERROR:

AddonInstalljob[scriptcommon.plugin.rache]: failed to download
pecial://home/addons/packages/scriptcommon.plugin.cache-2.5.8.zip
1:56:51.144 T:18446744071922112816 ERROR: CAddonInstalljob[plugin.video.sbs]:
ailed to install dependency script.common.plugin.cache
1:57:34.708 T:18446744072035686704 ERROR: CCurlFile::Open failed with code 404
or
 Ups://raw.githubusercontent.com/ares-fortress/repo/master/script.common.plugin.ca(i9675
11:57:34.709 7:18446744072035686704 ERROR:
CAddonInstalliob[script.common.plugin.cacha failed to download
special://home/addons/packages/script.common.plugin.cache-2.5.8.zip
11:57:34.723 7:18446744072035686704 ERROR:
CAddonInstalljob[plugin.video.abc_iview]: failed to install dependency
script.common.plugin.cache

**Comment by andybotting** [comment]
I've been update to reproduce this error yet.

I'm wondering if it's because you have another repository configured, which it might be trying to pull the common cache add-on from, rather than from the official Kodi repo.

I pulled my copy from http://mirrors.kodi.tv/addons/krypton/script.common.plugin.cache/script.common.plugin.cache-2.5.8.zip just now.

**Comment by anthony9999** [comment]
andy

thanks for your interest. downloaded this then tried to install  from zip.
Error was "failed to start commoncache

**Comment by andybotting** [comment]
failed to start isn't a fatal message. It will work fine as long as you got the add-on installed

**Comment by glennguy** [comment]
You guys should consider removing the illegal streaming repositories as
they are usually the culprit with a lot of errors, this case included. In
this case it seems Kodi is finding that the Ares repo has the cache add-on
but getting a 404 when it tries to download it. It has been in the news in
the last week that Ares repo has shutdown, which explains this behaviour.
Remove or disable the Ares repo and try installing our add-ons again.

I can guarantee that a fresh install of Kodi with only the official Kodi
repo and our repo installed would not have this issue.
