### ISSUE TITLE
Info Scraping

### ISSUE THREAD

**Issue by sween64** [aussieaddons/plugin.video.abc_iview#3080]
Can broadcast date be scraped and applied as date aired? This would help me set up some of my widgets. Thanks.

**Comment by andybotting** [comment]
I had a feeling we just used the only date that we were given by the API

Have you had a look at the data returned, does it actually contain what you're after?

**Comment by sween64** [comment]
No dates are displayed when the add-on is used on Kodi.

**Comment by glennguy** [comment]
@sween64 we're currently on the old API for the add-on which may or may not have air dates, but if the metadata is there shouldn't be a problem adding it in. We'll look at the new API soon though as it'd be nice to take advantage of the fancy fan art it has.

**Comment by glennguy** [comment]
@sween64 
I've had a look and the published date is there in the data, and we currently set it as the `aired` info label in Kodi - https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14
The Video Values table is the list of available fields that we can populate when building the directory listing in Kodi. Perhaps your widgets are looking at `premiered` or `dateadded`? When I bring up info for any of the program items in Estuary it shows the date under 'First aired' tag.

**Comment by sween64** [comment]
Thanks. I’m not sure why the details weren’t showing on Media Info view before but they are now. 

It still hasn’t fixed my custom widget issue on my Aura skin but that’s nothing to do with your add-on. I’ve set the sort order by “aired” and it hasn’t helped. Not to worry. 

Thanks for your help.
