### ISSUE TITLE
How to change default view?

### ISSUE THREAD

**Issue by brentonv** [aussieaddons/plugin.video.abc_iview#3081]
Wow no bugs since two years ago that's cool. I've just got a question I hope someone can answer. How can I modify the add-on to change default view type?

On my install iView content shows differently to all other on-demand add-ons and it's really hard to use. If I change the view type it affects all others so I'm hoping to change the setting in iView code.

Currently it looks like this where shows are missing the title and no series folder:

![IMG_20200109_204813](https://user-images.githubusercontent.com/2313757/72057499-9f230b00-3322-11ea-9cc6-d4839012cae9.jpg)

![IMG_20200109_205020](https://user-images.githubusercontent.com/2313757/72057535-a813dc80-3322-11ea-9dfa-a8df88b4dd2a.jpg) 

SBS and all others show like this:

![IMG_20200109_205135](https://user-images.githubusercontent.com/2313757/72057607-c2e65100-3322-11ea-9056-6527099cdd2f.jpg)

![IMG_20200109_205210](https://user-images.githubusercontent.com/2313757/72057646-d09bd680-3322-11ea-958d-337ab2c99267.jpg)

If anyone can assist I would appreciate it. Cheers

**Comment by glennguy** [comment]
What skin are you using? - just so I can replicate...

**Comment by brentonv** [comment]
Thanks Glen. I'm using Arctic Zephyr 2 by jurialmunkey set to horizontal menu.

**Comment by brentonv** [comment]
Looks like iView is using the Tv series layout which would be fine but in my case I would prefer to change it to episode view:

![IMG_20200109_222341](https://user-images.githubusercontent.com/2313757/72064049-2aa29900-332f-11ea-9ecf-f3e92ca8996a.jpg)

![IMG_20200109_222404](https://user-images.githubusercontent.com/2313757/72064095-45750d80-332f-11ea-9d76-62f10f3dd1bf.jpg)

**Comment by glennguy** [comment]
I can't get the same view as you - this is with 'poster showcase':
![zeyphr](https://user-images.githubusercontent.com/11909320/72065034-53c42900-3331-11ea-84aa-2c0ef3205e9e.jpg)

Freshly installed the skin.

In any case you can control how the 'series' are displayed if you like by editing the source. In the iview addon folder edit series.py in lib/resources and on [line 58](https://github.com/aussieaddons/plugin.video.abc_iview/blob/master/resources/lib/series.py#L58) change `tvshows` to `episodes`.

**Comment by brentonv** [comment]
Yeah odd. I can't get your view either. Similar. But yeah thanks heaps for the code.

**Comment by glennguy** [comment]
No worries. I've got Arctic Zephyr 2 v0.9.57-alpha1 fwiw
