### ISSUE TITLE
Add-on header/title missing

### ISSUE THREAD

**Issue by brentonv** [aussieaddons/plugin.video.abc_iview#3082]
Hi guys. No big deal but just noticed that iView and SBS are missing title info.

Here's example attached below. 9Now shows "9Now" in the heading but iView and SBS seem to default to "TV Shows" probably because the title isn't available. 

Like I said no big deal but it would be nice to know I'm in iView when I'm browsing it.

![IMG_20200117_102421](https://user-images.githubusercontent.com/2313757/72572222-f4a87a80-3915-11ea-8748-be37b45b4dc5.jpg)

Could someone maybe post the missing code so I can add it to my setup. Thanks

**Comment by glennguy** [comment]
Thanks for the report @brentonv 

The cause of this behaviour is the call to xbmcplugin.setContent in the function that builds the directory for Kodi. It looks like setting it to 'episodes' causes your skin to do this.

I've made a patch to categories.py in iview, should be in the development repo now for you to have a look at. The content is now set to 'videos'. Btw, valid options are [here](https://romanvm.github.io/Kodistubs/_autosummary/xbmcplugin.html#xbmcplugin.setContent) if you want to have a play. 

Estuary skin will show the content category as well as the addon name - perhaps a better solution is a feature request to the dev of your skin?

**Comment by brentonv** [comment]
Thankyou Glenn. Same also with SBS
