### ISSUE TITLE
ABC IView addon stopped working.

### ISSUE THREAD

**Issue by Tallguy297** [aussieaddons/plugin.video.abc_iview#3090]
Playback is no longer working on iView.
When I select any title, the Kodi gives the "Working" with spinning circles for a few seconds and then nothing.
I have removed the repo entirely and reinstalled just in case I had an older version.
I reinstalled this repo ... https://r.aussieaddons.com/repo-1.2.0.zip'
Tested again, programs will not play.

Thank you...

**Comment by glennguy** [comment]
Working fine here so there must be something on your system. If you can post a debug log we might be able to help:
https://kodi.wiki/view/Log_file/Easy

**Comment by Tallguy297** [comment]
As requested, here is a copy of my debug log...

[kodi.log](https://github.com/aussieaddons/plugin.video.abc_iview/files/10948669/kodi.log)

Thank you...

**Comment by Tallguy297** [comment]
I have fixed the problem with ABC IView.
I had to update the `kodi-inputstream-adaptive`

Thanks for your help...
